---
title: "MDP I"
output: word_document
date: "2025-02-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r librerias, include=FALSE}
install.packages("readxl")
library('readxl')
install.packages('dplyr')
library(dplyr)
```

```{r carga, echo=TRUE}
datos = read_excel("2022-2023_Football_Player_Stats.xlsx")
dim(datos)
head(datos, 3)
summary(datos)

descFut = data.frame("variable" = colnames(datos),
                      "tipo" = c("text", rep("categorical", 4), rep("numerical", 51)), stringsAsFactors = FALSE)
# Convertir variables de tipo string a tipo numérico según descFut
numerical_vars <- descFut$variable[descFut$tipo == "numerical"]

datos[numerical_vars] <- lapply(datos[numerical_vars], function(x) {
  as.numeric(as.character(x))
})

# eliminamos los datos que tengan MatchP < 5
datos <- datos[datos$MatchP >= 5, ]

# creamos un dataframe que contenga a los jugadores con nombres idénticos
duplicados = datos[duplicated(datos$Player) | duplicated(datos$Player, fromLast = TRUE), ]

# agrupamos por nombre y edad, y nos quedamos con el que haya jugado más minutos
duplicados2 = duplicados %>% group_by(Player, Age) %>% filter(Min == max(Min))
eliminar_dup = anti_join(duplicados, duplicados2, by = c("Player", "Min"))
datos <- anti_join(datos, eliminar_dup, by = c("Player", "Min"))
```

```{r analisis_estadistico, echo=TRUE}
summary(datos[,descFut$variable[descFut$tipo == "numerical"]])
mySD = apply(datos[,descFut$variable[descFut$tipo == "numerical"]], 2, sd)
myMU = colMeans(datos[,descFut$variable[descFut$tipo == "numerical"]])
myCV = mySD/myMU
sort(myCV)
```

